name: run build on master and tags
on:
  push:
    branches:
      - master
    tags:
      - ovirt-engine-ui-extensions-*
  workflow_dispatch:

jobs:
  build_offline:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: EL8
            container-image: quay.io/ovirt/buildcontainer:el8stream
          - name: EL9
            container-image: quay.io/ovirt/buildcontainer:el9stream

    name: ${{ matrix.name }} - test, build and publish rpm repo for the PR (ovirt-engine-nodejs-modules build)
    container:
      image: ${{ matrix.container-image }}

    env:
      OFFLINE_BUILD: 1

    steps:
      - name: Ensure latest ovirt-engine-nodejs-modules is installed
        run: |
          rpm -q --quiet ovirt-engine-nodejs-modules && ACTION=upgrade || ACTION=install
          dnf -y --disablerepo='*' --enablerepo='*ovirt*' $ACTION ovirt-engine-nodejs-modules

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Run packaging/build.sh
        run: |
          ./packaging/build.sh

      - name: Upload artifacts as rpm repo
        uses: ovirt/upload-rpms-action@v2
        with:
          directory: exported-artifacts/
