name: run build on master and tags
on:
  push:
    branches:
      - master
    tags:
      - ovirt-engine-ui-extensions-*
  workflow_dispatch:

jobs:
  build_offline:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: centos-stream-9
            shortcut: cs9
            container-name: el9stream
          - name: centos-stream-10
            shortcut: cs10
            container-name: el10stream

    name: ${{ matrix.name }} - test, build and publish rpm repo for the PR (ovirt-engine-nodejs-modules build)
    container:
      image: quay.io/ovirt/buildcontainer:${{ matrix.container-name }}

    env:
      OFFLINE_BUILD: 1

    steps:
      - name: Ensure latest ovirt-engine-nodejs-modules is installed
        run: |
          rpm -q --quiet ovirt-engine-nodejs-modules && ACTION=upgrade || ACTION=install
          dnf -y $ACTION ovirt-engine-nodejs-modules

      - name: Checkout sources
        uses: ovirt/checkout-action@main

      - name: Mark git repo as safe
        run: git config --global --add safe.directory $(pwd)

      - name: Run packaging/build.sh
        run: |
          ./packaging/build.sh

      - name: Upload artifacts as rpm repo
        uses: ovirt/upload-rpms-action@main
        with:
          directory: exported-artifacts/
